### PR TITLE
PodSpec revisioni to avoid importing the Info.plist

### PR DESCRIPTION
**Pull request by JoelGerboreLaser**
Updated the podspec: removed the import of the Info.plist to avoid build problems

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you for sharing. Can you please say if there is an source where you got this approach from?

Please see the note here https://github.com/fulldecent/FDTake#contributing

^ There are many projects that depend on this build instruction so if it wrong I would like to fix it upstream first.

**Comment by JoelGerboreLaser** [comment]
I've made another small modification to correctly separate the code files (.swift, .h, .m) in pod spec source files and .strings in resource.

The upstream project already in the **__PROJECT_NAME__.podspec** has a more specific import in s.source_files = 'Source/*.{h,m,swift}'. 
AlamoFire too uses a more specific regex to import only correct code files  "source_files": "Source/*.swift"

**Comment by fulldecent** [comment]
Looks great, thank you.

**Comment by JoelGerboreLaser** [comment]
Thanks!
Will you release an updated podspec on Cocoapods?

**Comment by fulldecent** [comment]
I'm having some trouble building/releasing.

Just to get my bearings straight I started back upstream at https://github.com/fulldecent/swift4-module-template/pull/43

**Pull request merged**
