### PR TITLE
New project structure to solve localization problems

### PR DESCRIPTION
**Pull request by filograno**
The code for localization works well.
To solve the issue #100 I have modified the project structure:
- removing the FDTake.xcworkspace file
- creating a new Podfile for the 'iOS Example'
- running the 'pod install' command to create a new 'iOS Example.xcworkspace' file in the 'iOS Example' folder
- adding all the supported languages in 'iOS Example' project

With this modifications, to run the example: open the 'iOS Example.xcworkspace' file in the 'iOS Example' folder.

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you very much. I will review this effort and see how it works. 

The colurrent project layout should follow swift3-module-template, which is strongly motivated by how AlamoFire lays out their project. 

Would you please be able to explain if this change is compatible with how that project is laid out. Any other discussion you have will be helpful because I may want to make changes to swift3-module-template as well.

**Comment by filograno** [comment]
I've reorganized the project seeing the structure of a project I'm currently collaborating:[https://github.com/Moya/Moya](url).
However a good structure for a project like FDTake, could be the default structure that cocoapods advices at this link: [https://guides.cocoapods.org/making/using-pod-lib-create.html](url)

When you create a new pod (public or private) you could run `pod lib create PROJECT_NAME` to scaffold a new project that works well with both Cocoapods and Carthage.

So far swift3-module-template is slightly different from the default cocoapod template structure.

Furthermore, cocoapods allows to use a different template using the `--template-url=URL`  parameter in `pod lib create PROJECT_NAME` command; so you can modify swift3-module-template to be a cocoapods-compatible template.

**Comment by fulldecent** [comment]
I am on the pod template team. We have a PR open to make swift3-module-template be the new default for cocoa pods. Also s3mt is currently compatible with pod lib create as your describe.

**Comment by filograno** [comment]
Ok, I didn't know about your collaboration on pod template. Anyway, are you sure that swift3-module-template does not break the localization, like in FDTake?

**Comment by fulldecent** [comment]
I am not sure yet. If localization on the template is broken that is a much bigger problem that will affect MANY people (like all of cocoapods). I would want to fix it there first and then fix FDTake second.

FYI, the whole point of swift3-module-template is that project layout is too complicated and undocumented. It is a recipe that explains exactly how to get from XCode new project to something you can actually use.

**Comment by fulldecent** [comment]
First, my apologies. I have added explicit documentation of this contribution guidelines right at the bottom of the readme. I haven't started looking at this yet since I'm still on travel but I did want to help with that. Please stay tuned and thank you for your help!

**Comment by fulldecent** [comment]
Ok, I have started looking at this mainly from the perspective of how can I update swift3-module-template to demonstrate correct usage of localized strings in the module part of the project.

The first question is: should all great module projects have localized strings? Probably not. Therefore localized strings should not be in swift3-module-template. Perhaps I can add a wiki page on that project which augments the "Recipe" so that downstream projects (like FDTake) have a correct and verified, documented approach to localizing strings in the module.

(This roundabout and fully-documented "recipe" approach is better for me because I keep why we made certain Xcdoe projects layout design decisions.) 

I am dropping the ball at this point because I am not sure exactly how to accomplish the above.

**Comment by filograno** [comment]
I think that a template for a new pod project must ensure that the localization works, because could be used both for great projects (like Alamofire) and downstream projects (like FDTake). 

Anyway, when I made this pull request I didn't know that the project structure was related to swift3-module-template and my modification could impact this project too. My goal was to solve the issue  #100.

**Comment by fulldecent** [comment]
Thank you and I do appreciate your help.

I do want to study it and incorporate the fix into this project, though just not in its current form.

**Comment by fulldecent** [comment]
Closing this out because this is not the right approach for this project. I think we can get it in there a different way, but not this way. Thank you for working on this.

**Pull request closed without merging**
