### PR TITLE
Added QualityIndexes

### PR DESCRIPTION
**Pull request by haydenholligan**
I wasn't sure where to put the file so if you want it in a different location just let me know!

### CODE REVIEW

**Comment by fulldecent** [comment]
Please update CHANGELOG and integrate into Travis as done in these two commits:

https://github.com/fulldecent/FDBarGuage/commits/master/Tests/CheckCocoaPodsQualityIndexes.rb

**Comment by haydenholligan** [comment]
Did you want me to add this as a new version (0.3.4) in the changelog?

**Comment by fulldecent** [comment]
Yes please

**Comment by fulldecent** [comment]
No actually. You just add the notes under master and then I relabel it when doing a release. Thank you.

**Comment by haydenholligan** [comment]
It should be good now. Script is showing up in Travis CI. Let me know if there's anything else to be done

**Comment by fulldecent** [comment]
Looks great, merging, thanks!

**Pull request merged**
