### PR TITLE
Bug localization bundle on v 3.0

### PR DESCRIPTION
**Pull request by LivioGama**
Fix localization bundle when using FDTake 3.0 as a Pod (problem not present in example projet which use local Pod path)

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you, merged!

**Comment by fulldecent** [comment]
Pushed new version 0.3.1 including this fix

**Comment by narekyan** [comment]
hmm I have error here on 0.3.2

screen shot 2016-05-30 at 21 36 26

**Comment by fulldecent** [comment]
Thank you, is anyone else seeing this bug?

**Comment by narekyan** [comment]
Hi 
I have checked
Problem is with latest cocoapods

**Pull request merged**
