### PR TITLE
Swift 3 conversion

### PR DESCRIPTION
**Pull request by AnthonyMDev**
The swift 3 conversion is completed here for you. The framework should build and operate properly when linked to another application.

There is an Xcode linker error when running the example project that I wasn't able to figure out. You may have more luck with that. 

````
dyld: Library not loaded: @rpath/FDTake.framework/FDTake
  Referenced from: /Users/Anthony/Library/Developer/CoreSimulator/Devices/4CEB8CFD-4B0F-45E8-846D-09CF7472E62E/data/Containers/Bundle/Application/68D448FF-F227-4B53-A7E0-4D33C458B135/FDTake_Example.app/FDTake_Example
  Reason: image not found
````

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you, I am reviewing this now

**Comment by fulldecent** [comment]
If anyone wants to watch or get involved
https://www.youtube.com/watch?v=nkGIlDStD7Q

**Comment by fulldecent** [comment]
Got it running and working with iOS example, now cleaning up project

**Comment by fulldecent** [comment]
Got everything working except localization. Will need assistance.

**Comment by AnthonyMDev** [comment]
I've never worked with localization myself. Sorry I can't be of help there. :/

**Pull request merged**
